version: '3'
services:
  frontend:
    image: mhart/alpine-node:12
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    command:
      >
        sh -i -c -e
        "
        yarn install --frozen-lockfile;
        yarn start:dev;
        "
